name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: 📂 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.HOST_FTP }}
          username: ${{ secrets.USER_FTP }}
          password: ${{ secrets.PASS_FTP }}
          port: 21
          protocol: ftp
          local-dir: dist/
          server-dir: public_html/tv/
